"use strict";
(() => {
  const rows = [
    [
      "fork",
      "N",
      "3q3k/8/8/4N3/8/8/8/K7 w - - 0 1",
      "e5f7",
      ["Çatal", "Fork", "Horquilla", "Fourchette", "شوكة", "Gabel"],
      [
        "Atı f7’ye getir. Şaha ve vezire aynı anda saldırır.",
        "Move the knight to f7, attacking king and queen together.",
        "Mueve el caballo a f7: ataca al rey y a la dama.",
        "Jouez le cavalier en f7 : il attaque le roi et la dame.",
        "حرّك الحصان إلى f7 ليهاجم الملك والوزير معًا.",
        "Ziehe den Springer nach f7: Er greift König und Dame an.",
      ],
    ],
    [
      "pin",
      "B",
      "4k3/8/2n5/8/2B5/8/8/K7 w - - 0 1",
      "c4b5",
      ["Açmaz", "Pin", "Clavada", "Clouage", "تثبيت", "Fesselung"],
      [
        "Fili b5’e getir. c6’daki at oynarsa şahı açıkta kalır; bu yüzden hareket edemez.",
        "Move the bishop to b5. The knight on c6 cannot move without exposing its king.",
        "Lleva el alfil a b5. El caballo c6 no puede moverse sin exponer a su rey.",
        "Jouez le fou en b5. Le cavalier c6 ne peut bouger sans exposer son roi.",
        "حرّك الفيل إلى b5. لا يستطيع حصان c6 التحرك وكشف ملكه.",
        "Ziehe den Läufer nach b5. Der Springer c6 darf seinen König nicht freilegen.",
      ],
    ],
    [
      "skewer",
      "R",
      "4q3/8/4k3/8/8/8/8/R6K w - - 0 1",
      "a1e1",
      ["Şiş", "Skewer", "Enfilada", "Enfilade", "سيخ", "Spieß"],
      [
        "Kaleyi e1’e getir. Şah kaçınca arkasındaki vezir alınabilir.",
        "Move the rook to e1. When the king moves, the queen behind it is exposed.",
        "Mueve la torre a e1. Al moverse el rey, la dama queda expuesta.",
        "Jouez la tour en e1. Quand le roi part, la dame derrière lui est exposée.",
        "حرّك الرخ إلى e1. عندما يتحرك الملك ينكشف الوزير خلفه.",
        "Ziehe den Turm nach e1. Nach dem Königszug ist die Dame dahinter angegriffen.",
      ],
    ],
    [
      "discovered",
      "B",
      "4k3/8/8/8/8/8/4B3/K3R3 w - - 0 1",
      "e2f3",
      [
        "Açarak şah",
        "Discovered check",
        "Jaque descubierto",
        "Échec à la découverte",
        "كش بالكشف",
        "Abzugsschach",
      ],
      [
        "Fili f3’e götürerek kalenin önünü aç. e1’deki kale şah çeker.",
        "Move the bishop to f3, uncovering a check from the rook on e1.",
        "Mueve el alfil a f3 para descubrir el jaque de la torre e1.",
        "Jouez le fou en f3 pour découvrir l’échec de la tour e1.",
        "حرّك الفيل إلى f3 لكشف كش الرخ في e1.",
        "Ziehe den Läufer nach f3 und öffne die Schachlinie des Turms e1.",
      ],
    ],
    [
      "double",
      "B",
      "4k3/8/8/8/8/8/4B3/K3R3 w - - 0 1",
      "e2b5",
      [
        "Çifte şah",
        "Double check",
        "Jaque doble",
        "Échec double",
        "كش مزدوج",
        "Doppelschach",
      ],
      [
        "Fili b5’e getir. Fil ve kale birlikte şah çeker. Rakip şahını oynatmak zorundadır.",
        "Move the bishop to b5. Bishop and rook both give check; the king must move.",
        "Lleva el alfil a b5. Alfil y torre dan jaque; el rey debe moverse.",
        "Jouez le fou en b5. Fou et tour donnent échec ; le roi doit bouger.",
        "حرّك الفيل إلى b5. الفيل والرخ يعطيان كشًا ويجب تحريك الملك.",
        "Ziehe den Läufer nach b5. Läufer und Turm bieten Schach; der König muss ziehen.",
      ],
    ],
    [
      "block",
      "B",
      "4r3/7k/8/8/8/2B5/8/4K3 w - - 0 1",
      "c3e5",
      [
        "Araya girme",
        "Interposition",
        "Interposición",
        "Interposition",
        "حجب الهجوم",
        "Dazwischenziehen",
      ],
      [
        "Şah tehdit altında. Fili e5’e getirerek kalenin yolunu kapat.",
        "Your king is in check. Block the rook by moving the bishop to e5.",
        "Tu rey está en jaque. Bloquea la torre con el alfil en e5.",
        "Votre roi est en échec. Bloquez la tour avec le fou en e5.",
        "ملكك في كش. احجب الرخ بتحريك الفيل إلى e5.",
        "Dein König steht im Schach. Blockiere den Turm mit Le5.",
      ],
    ],
    [
      "captureDefender",
      "R",
      "6k1/5ppp/8/8/8/8/8/R5K1 w - - 0 1",
      "a1a8",
      [
        "Arka sıra matı",
        "Back-rank mate",
        "Mate de pasillo",
        "Mat du couloir",
        "مات الصف الخلفي",
        "Grundreihenmatt",
      ],
      [
        "Siyah şahın önünü kendi piyonları kapatıyor. Kaleyi a8’e getirerek mat et.",
        "Black’s pawns block the king’s escape. Play Ra8 for mate.",
        "Los peones negros bloquean al rey. Juega Ta8 y da mate.",
        "Les pions noirs bloquent leur roi. Jouez Ta8 pour mater.",
        "بيادق الأسود تمنع هروب الملك. العب Ra8 للمات.",
        "Die schwarzen Bauern versperren dem König den Weg. Ta8 setzt matt.",
      ],
    ],
    [
      "longCastle",
      "K",
      "4k3/8/8/8/8/8/8/R3K3 w Q - 0 1",
      "e1c1",
      [
        "Uzun rok",
        "Queenside castling",
        "Enroque largo",
        "Grand roque",
        "التبييت الطويل",
        "Lange Rochade",
      ],
      [
        "Şahı c1’e getir. Kale d1’e geçer. b1 de boş olmalıdır; şah e1, d1 ve c1’de tehdit altında olamaz.",
        "Move the king to c1; the rook goes to d1. b1 must also be empty; e1, d1 and c1 must be safe.",
        "Mueve el rey a c1 y la torre va a d1. b1 debe estar libre; e1, d1 y c1 deben ser seguras.",
        "Jouez le roi en c1, la tour va en d1. b1 doit être libre ; e1, d1 et c1 doivent être sûres.",
        "حرّك الملك إلى c1 والرخ إلى d1. يجب أن يكون b1 خاليًا وأن تكون e1 وd1 وc1 آمنة.",
        "Ziehe den König nach c1; der Turm geht nach d1. b1 muss frei sein, e1, d1 und c1 sicher.",
      ],
    ],
    [
      "underpromotion",
      "P",
      "7k/4P3/8/8/8/8/8/K7 w - - 0 1",
      "e7e8n",
      [
        "Ata terfi",
        "Knight promotion",
        "Promoción a caballo",
        "Promotion en cavalier",
        "الترقية إلى حصان",
        "Springerumwandlung",
      ],
      [
        "Terfide vezir zorunlu değildir. e8’e ilerle ve atı seç. At, vezirin ulaşamadığı karelere saldırabilir.",
        "Promotion need not be to a queen. Move to e8 and choose a knight, which attacks different squares.",
        "No es obligatorio elegir dama. Avanza a e8 y elige caballo, que ataca otras casillas.",
        "La dame n’est pas obligatoire. Avancez en e8 et choisissez le cavalier, qui attaque autrement.",
        "الترقية إلى وزير ليست إلزامية. تقدم إلى e8 واختر الحصان الذي يهاجم مربعات مختلفة.",
        "Eine Dame ist nicht vorgeschrieben. Ziehe nach e8 und wähle einen Springer mit anderen Angriffsfeldern.",
      ],
    ],
    [
      "escape",
      "K",
      "7k/8/8/8/8/8/8/Kr6 w - - 0 1",
      "a1b1",
      [
        "Saldıranı alma",
        "Capture the attacker",
        "Capturar al atacante",
        "Prendre l’attaquant",
        "أخذ المهاجم",
        "Angreifer schlagen",
      ],
      [
        "b1’deki kale korunmuyor. Şahla kaleyi alıp şahtan kurtul.",
        "The rook on b1 is undefended. Capture it with your king to escape check.",
        "La torre b1 está indefensa. Captúrala con el rey para salir del jaque.",
        "La tour b1 n’est pas protégée. Prenez-la avec le roi pour sortir de l’échec.",
        "الرخ في b1 غير محمي. خذه بالملك للخروج من الكش.",
        "Der Turm b1 ist ungedeckt. Schlage ihn mit dem König und wehre das Schach ab.",
      ],
    ],
    [
      "center",
      "P",
      Chess.initial,
      "e2e4",
      ["Merkez", "Center", "Centro", "Centre", "المركز", "Zentrum"],
      [
        "e4 ve d4 merkez kareleridir. e2–e4 oynayarak merkezde yer kazan ve filin yolunu aç.",
        "e4 and d4 are central squares. Play e2–e4 to claim space and open your bishop.",
        "e4 y d4 son centrales. Juega e2–e4 para ganar espacio y abrir el alfil.",
        "e4 et d4 sont centrales. Jouez e2–e4 pour gagner de l’espace et ouvrir le fou.",
        "e4 وd4 مربعان مركزيان. العب e2–e4 لكسب مساحة وفتح الفيل.",
        "e4 und d4 sind Zentrumsfelder. Spiele e2–e4, gewinne Raum und öffne den Läufer.",
      ],
    ],
    [
      "development",
      "N",
      "rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq e6 0 2",
      "g1f3",
      [
        "Gelişim",
        "Development",
        "Desarrollo",
        "Développement",
        "التطوير",
        "Entwicklung",
      ],
      [
        "Atı f3’e çıkar. Merkeze yaklaşırken e5 piyonuna saldırır. Açılışta taşlarını oyuna kat.",
        "Develop the knight to f3. It approaches the center and attacks e5. Bring pieces into play in the opening.",
        "Desarrolla el caballo a f3. Se acerca al centro y ataca e5. Activa tus piezas en la apertura.",
        "Développez le cavalier en f3. Il vise le centre et attaque e5. Activez vos pièces à l’ouverture.",
        "طوّر الحصان إلى f3 ليقترب من المركز ويهاجم e5. أدخل قطعك إلى اللعب في الافتتاح.",
        "Entwickle den Springer nach f3. Er steht zentral und greift e5 an. Bringe deine Figuren ins Spiel.",
      ],
    ],
    [
      "opposition",
      "K",
      "8/4k3/8/8/4K3/8/4P3/8 w - - 0 1",
      "e4e5",
      [
        "Opozisyon",
        "Opposition",
        "Oposición",
        "Opposition",
        "المقابلة",
        "Opposition",
      ],
      [
        "Şahı e5’e getir. Şahlar arasında bir kare kalır; sıradaki siyah şah yana çekilmek zorundadır.",
        "Move the king to e5. One square separates the kings; Black must give way.",
        "Mueve el rey a e5. Queda una casilla entre reyes; las negras deben ceder.",
        "Jouez le roi en e5. Une case sépare les rois ; les noirs doivent céder.",
        "حرّك الملك إلى e5. يفصل مربع واحد الملكين وعلى الأسود التراجع جانبًا.",
        "Ziehe den König nach e5. Ein Feld trennt die Könige; Schwarz muss ausweichen.",
      ],
    ],
    [
      "passed",
      "P",
      "7k/8/4P3/8/8/8/8/K7 w - - 0 1",
      "e6e7",
      [
        "Geçer piyon",
        "Passed pawn",
        "Peón pasado",
        "Pion passé",
        "البيدق المار",
        "Freibauer",
      ],
      [
        "Önünde veya bitişik sütunlarda rakip piyonu olmayan piyon geçerdir. e7’ye ilerle.",
        "A passed pawn has no enemy pawn ahead on its file or adjacent files. Advance to e7.",
        "Un peón pasado no tiene peones enemigos delante ni en columnas vecinas. Avanza a e7.",
        "Un pion passé n’a aucun pion adverse devant lui ni sur les colonnes voisines. Avancez en e7.",
        "البيدق المار لا يواجه بيدقًا عدوًا أمامه أو في الأعمدة المجاورة. تقدم إلى e7.",
        "Ein Freibauer hat vor sich auf seiner und den Nachbarlinien keine gegnerischen Bauern. Ziehe nach e7.",
      ],
    ],
    [
      "rookEnd",
      "R",
      "7k/8/5K2/8/8/8/8/R7 w - - 0 1",
      "a1a7",
      [
        "Şahla işbirliği",
        "King coordination",
        "Coordinación del rey",
        "Coordination du roi",
        "تنسيق الملك",
        "Königskoordination",
      ],
      [
        "Kaleyi a7’ye getir. Rakip şahın alanını daralt; kendi şahını da saldırıya yaklaştır.",
        "Move the rook to a7. Restrict the enemy king and bring your own king into the attack.",
        "Lleva la torre a a7. Limita al rey rival y acerca tu rey al ataque.",
        "Jouez la tour en a7. Limitez le roi adverse et rapprochez votre roi.",
        "حرّك الرخ إلى a7. ضيّق مساحة ملك الخصم وقرّب ملكك للهجوم.",
        "Ziehe den Turm nach a7. Begrenze den gegnerischen König und führe deinen König heran.",
      ],
    ],
    [
      "avoidPat",
      "Q",
      "7k/5Q2/5K2/8/8/8/8/8 w - - 0 1",
      "f7g7",
      [
        "Patı önleme",
        "Avoid stalemate",
        "Evitar el ahogado",
        "Éviter le pat",
        "تجنب الخنق",
        "Patt vermeiden",
      ],
      [
        "Şah çekmeden rakibi hamlesiz bırakmak pattır. Veziri g7’ye getir: bu kez şah da tehdit altında, sonuç mat.",
        "Leaving no move without check is stalemate. Qg7 also checks the king, so it is mate.",
        "Dejar sin jugadas pero sin jaque es ahogado. Dg7 da jaque y es mate.",
        "Sans coup légal mais sans échec, c’est pat. Dg7 donne aussi échec : c’est mat.",
        "منع كل النقلات دون كش يعني الخنق. Qg7 يعطي كشًا أيضًا، لذا هو مات.",
        "Zugunfähigkeit ohne Schach ist Patt. Dg7 bietet auch Schach und ist deshalb Matt.",
      ],
    ],
    [
      "exchange",
      "R",
      "7k/8/8/8/3q4/8/8/K2R4 w - - 0 1",
      "d1d4",
      [
        "Taş değeri",
        "Piece value",
        "Valor de las piezas",
        "Valeur des pièces",
        "قيمة القطع",
        "Figurenwert",
      ],
      [
        "Yaklaşık değerler: piyon 1, at ve fil 3, kale 5, vezir 9. Kaleyle d4’teki korunmasız veziri al.",
        "Approximate values: pawn 1, knight and bishop 3, rook 5, queen 9. Capture the undefended queen on d4.",
        "Valores aproximados: peón 1, caballo y alfil 3, torre 5, dama 9. Captura la dama indefensa en d4.",
        "Valeurs indicatives : pion 1, cavalier et fou 3, tour 5, dame 9. Prenez la dame non protégée en d4.",
        "قيم تقريبية: بيدق 1، حصان وفيل 3، رخ 5، وزير 9. خذ الوزير غير المحمي في d4.",
        "Richtwerte: Bauer 1, Springer und Läufer 3, Turm 5, Dame 9. Schlage die ungedeckte Dame auf d4.",
      ],
    ],
    [
      "finish",
      "Q",
      "7k/8/5KQ1/8/8/8/8/8 w - - 0 1",
      "g6g7",
      [
        "Son kontrol",
        "Final check",
        "Comprobación final",
        "Dernière vérification",
        "الفحص الأخير",
        "Letzte Prüfung",
      ],
      [
        "Şah, alma ve tehditleri sırayla kontrol et. Rakibin kaçış karelerini say; tek hamlede matı bul.",
        "Check checks, captures and threats. Count the king’s escape squares and find mate in one.",
        "Revisa jaques, capturas y amenazas. Cuenta las salidas del rey y encuentra mate en una.",
        "Examinez échecs, prises et menaces. Comptez les fuites du roi et trouvez le mat en un.",
        "افحص الكش والأخذ والتهديدات. احسب مربعات الهروب واعثر على مات في نقلة.",
        "Prüfe Schachs, Schlagzüge und Drohungen. Zähle die Fluchtfelder und finde Matt in einem Zug.",
      ],
    ],
  ];
  for (const [name, piece, fen, move, title, text] of rows) {
    ChessText.extend({ [name]: title });
    ChessLessons.push({ name, piece, fen, move, text });
  }
})();
