"use strict";
ChessText.extend({
  academy: ["Öğren", "Learn", "Aprender", "Apprendre", "تعلّم", "Lernen"],
  balanced: [
    "Dengeli",
    "Balanced",
    "Equilibrado",
    "Équilibré",
    "متوازن",
    "Ausgewogen",
  ],
  attacking: [
    "Saldırgan",
    "Attacking",
    "Atacante",
    "Offensif",
    "هجومي",
    "Angriff",
  ],
  positional: [
    "Konumsal",
    "Positional",
    "Posicional",
    "Positionnel",
    "تمركزي",
    "Positionell",
  ],
  defensive: [
    "Savunmacı",
    "Defensive",
    "Defensivo",
    "Défensif",
    "دفاعي",
    "Defensiv",
  ],
});
ChessText.extend({
  mateOne: [
    "Tek hamlede mat",
    "Mate in one",
    "Mate en una",
    "Mat en un",
    "مات في نقلة",
    "Matt in einem Zug",
  ],
  mateTwo: [
    "İki hamlede mat",
    "Mate in two",
    "Mate en dos",
    "Mat en deux",
    "مات في نقلتين",
    "Matt in zwei Zügen",
  ],
  losses: [
    "Mağlubiyet",
    "Losses",
    "Derrotas",
    "Défaites",
    "الخسائر",
    "Niederlagen",
  ],
  draws: ["Beraberlik", "Draws", "Tablas", "Nulles", "التعادلات", "Remis"],
  winRate: [
    "Kazanma oranı",
    "Win rate",
    "Victorias (%)",
    "Taux de victoire",
    "نسبة الفوز",
    "Siegquote",
  ],
  botStats: [
    "Bot karşılaşmaları",
    "Bot matches",
    "Partidas contra bots",
    "Parties contre les bots",
    "مباريات الحاسوب",
    "Bot-Partien",
  ],

  profile: ["Profil", "Profile", "Perfil", "Profil", "الملف الشخصي", "Profil"],
  edit: ["Düzenle", "Edit", "Editar", "Modifier", "تعديل", "Bearbeiten"],
  name: ["Ad", "Name", "Nombre", "Nom", "الاسم", "Name"],
  save: ["Kaydet", "Save", "Guardar", "Enregistrer", "حفظ", "Speichern"],
  avatar: ["Avatar", "Avatar", "Avatar", "Avatar", "الصورة", "Avatar"],
  quick: [
    "Hızlı karşılaşma",
    "Quick match",
    "Partida rápida",
    "Partie rapide",
    "مباراة سريعة",
    "Schnelle Partie",
  ],
  puzzles: [
    "Bulmacalar",
    "Puzzles",
    "Problemas",
    "Problèmes",
    "الألغاز",
    "Aufgaben",
  ],
  daily: [
    "Günlük bulmaca",
    "Daily puzzle",
    "Problema diario",
    "Problème du jour",
    "لغز اليوم",
    "Tagesaufgabe",
  ],
  streak: [
    "Günlük seri",
    "Daily streak",
    "Racha diaria",
    "Série quotidienne",
    "السلسلة اليومية",
    "Tagesserie",
  ],
  days: ["gün", "days", "días", "jours", "أيام", "Tage"],
  activity: [
    "Bir ders, bulmaca veya maç tamamla.",
    "Complete a lesson, puzzle or match.",
    "Completa una lección, problema o partida.",
    "Terminez une leçon, un problème ou une partie.",
    "أكمل درسًا أو لغزًا أو مباراة.",
    "Schließe eine Lektion, Aufgabe oder Partie ab.",
  ],
  todayDone: [
    "Bugün tamamlandı",
    "Completed today",
    "Completado hoy",
    "Terminé aujourd’hui",
    "اكتمل اليوم",
    "Heute abgeschlossen",
  ],
  chapter: ["Bölüm", "Chapter", "Capítulo", "Chapitre", "الفصل", "Kapitel"],
  level: ["Seviye", "Level", "Nivel", "Niveau", "المستوى", "Stufe"],
  stats: [
    "İstatistikler",
    "Statistics",
    "Estadísticas",
    "Statistiques",
    "الإحصاءات",
    "Statistik",
  ],
  history: [
    "Maç geçmişi",
    "Match history",
    "Historial",
    "Historique",
    "سجل المباريات",
    "Partieverlauf",
  ],
  matches: ["Maç", "Matches", "Partidas", "Parties", "المباريات", "Partien"],
  victories: [
    "Galibiyet",
    "Wins",
    "Victorias",
    "Victoires",
    "الانتصارات",
    "Siege",
  ],
  solved: ["Çözülen", "Solved", "Resueltos", "Résolus", "المحلولة", "Gelöst"],
  reward: [
    "Ödül",
    "Reward",
    "Recompensa",
    "Récompense",
    "المكافأة",
    "Belohnung",
  ],
  boardTheme: ["Tahta", "Board", "Tablero", "Échiquier", "الرقعة", "Brett"],
  background: [
    "Arka plan",
    "Background",
    "Fondo",
    "Arrière-plan",
    "الخلفية",
    "Hintergrund",
  ],
  appearance: [
    "Tahta ve ortam",
    "Board & setting",
    "Tablero y entorno",
    "Échiquier et décor",
    "الرقعة والبيئة",
    "Brett und Umgebung",
  ],
  forest: ["Orman", "Forest", "Bosque", "Forêt", "الغابة", "Wald"],
  sand: ["Kum", "Sand", "Arena", "Sable", "الرمال", "Sand"],
  ocean: ["Okyanus", "Ocean", "Océano", "Océan", "المحيط", "Ozean"],
  ember: ["Köz", "Ember", "Brasa", "Braise", "الجمر", "Glut"],
  stone: ["Taş", "Stone", "Piedra", "Pierre", "الحجر", "Stein"],
  plain: ["Düz", "Plain", "Liso", "Uni", "سادة", "Einfarbig"],
  mountains: [
    "Dağlar",
    "Mountains",
    "Montañas",
    "Montagnes",
    "الجبال",
    "Berge",
  ],
  arches: ["Kemerler", "Arches", "Arcos", "Arches", "الأقواس", "Bögen"],
  stars: ["Yıldızlar", "Stars", "Estrellas", "Étoiles", "النجوم", "Sterne"],
  foundations: [
    "Temeller",
    "Foundations",
    "Fundamentos",
    "Fondamentaux",
    "الأساسيات",
    "Grundlagen",
  ],
  tactics: [
    "Taktikler",
    "Tactics",
    "Tácticas",
    "Tactiques",
    "التكتيكات",
    "Taktik",
  ],
  endgames: [
    "Strateji ve oyun sonu",
    "Strategy & endgames",
    "Estrategia y finales",
    "Stratégie et finales",
    "الاستراتيجية والنهايات",
    "Strategie und Endspiele",
  ],
  mateIn: [
    "hamlede mat",
    "moves to mate",
    "jugadas para mate",
    "coups pour mater",
    "نقلات للمات",
    "Züge bis Matt",
  ],
  solve: ["Çöz", "Solve", "Resolver", "Résoudre", "حل", "Lösen"],
  nextPuzzle: [
    "Sonraki bulmaca",
    "Next puzzle",
    "Siguiente problema",
    "Problème suivant",
    "اللغز التالي",
    "Nächste Aufgabe",
  ],
  wrongMove: [
    "Başka bir hamle dene.",
    "Try another move.",
    "Prueba otra jugada.",
    "Essayez un autre coup.",
    "جرّب نقلة أخرى.",
    "Versuche einen anderen Zug.",
  ],
  puzzleGoal: [
    "Belirtilen hamle sayısında mat et. Rakibin yanıtı otomatik oynanır.",
    "Checkmate within the stated number of moves. The opponent replies automatically.",
    "Da mate en los movimientos indicados. El rival responde automáticamente.",
    "Matez dans le nombre de coups indiqué. La réponse adverse est automatique.",
    "حقق المات بعدد النقلات المحدد. يرد الخصم تلقائيًا.",
    "Setze in der angegebenen Zugzahl matt. Der Gegner antwortet automatisch.",
  ],
  emptyHistory: [
    "Henüz tamamlanmış maç yok.",
    "No completed matches yet.",
    "Aún no hay partidas terminadas.",
    "Aucune partie terminée.",
    "لا توجد مباريات مكتملة بعد.",
    "Noch keine abgeschlossenen Partien.",
  ],
  replay: [
    "Maçı incele",
    "Review match",
    "Revisar partida",
    "Revoir la partie",
    "راجع المباراة",
    "Partie ansehen",
  ],
  first: [
    "İlk hamle",
    "First move",
    "Primera jugada",
    "Premier coup",
    "النقلة الأولى",
    "Erster Zug",
  ],
  previous: ["Önceki", "Previous", "Anterior", "Précédent", "السابق", "Zurück"],
  following: ["Sonraki", "Next", "Siguiente", "Suivant", "التالي", "Weiter"],
  last: [
    "Son hamle",
    "Last move",
    "Última jugada",
    "Dernier coup",
    "النقلة الأخيرة",
    "Letzter Zug",
  ],
  startGame: [
    "Oyunu başlat",
    "Start game",
    "Iniciar partida",
    "Lancer la partie",
    "ابدأ المباراة",
    "Partie starten",
  ],
  chooseMode: [
    "Oyun seç",
    "Choose mode",
    "Elige modo",
    "Choisir un mode",
    "اختر النمط",
    "Modus wählen",
  ],
  locked: [
    "Önceki bulmacayı tamamla",
    "Complete the previous puzzle",
    "Completa el problema anterior",
    "Terminez le problème précédent",
    "أكمل اللغز السابق",
    "Löse die vorherige Aufgabe",
  ],
  journey: [
    "Bulmaca yolu",
    "Puzzle path",
    "Ruta de problemas",
    "Parcours de problèmes",
    "مسار الألغاز",
    "Aufgabenpfad",
  ],
  lessonProgress: [
    "Eğitim",
    "Learning",
    "Aprendizaje",
    "Apprentissage",
    "التعلم",
    "Lernen",
  ],
  noName: ["Oyuncu", "Player", "Jugador", "Joueur", "لاعب", "Spieler"],
  chapterNames: [
    [
      "Bahçe",
      "Kıyı",
      "Kanyon",
      "Vadi",
      "Kuleler",
      "Liman",
      "Zirve",
      "Çöl",
      "Gece",
      "Hisar",
    ],
    [
      "Garden",
      "Coast",
      "Canyon",
      "Valley",
      "Towers",
      "Harbor",
      "Summit",
      "Desert",
      "Night",
      "Citadel",
    ],
    [
      "Jardín",
      "Costa",
      "Cañón",
      "Valle",
      "Torres",
      "Puerto",
      "Cumbre",
      "Desierto",
      "Noche",
      "Ciudadela",
    ],
    [
      "Jardin",
      "Côte",
      "Canyon",
      "Vallée",
      "Tours",
      "Port",
      "Sommet",
      "Désert",
      "Nuit",
      "Citadelle",
    ],
    [
      "الحديقة",
      "الساحل",
      "الوادي",
      "السهول",
      "الأبراج",
      "الميناء",
      "القمة",
      "الصحراء",
      "الليل",
      "القلعة",
    ],
    [
      "Garten",
      "Küste",
      "Schlucht",
      "Tal",
      "Türme",
      "Hafen",
      "Gipfel",
      "Wüste",
      "Nacht",
      "Festung",
    ],
  ],
  streakHelp: [
    "Tamamlanan ders ve bulmacalar, matla biten maçlar veya en az 10 yarım hamle oynanmış biten maçlar seriye sayılır. Beş dakikalık hızlı karşılaşma da dahildir.",
    "Completed lessons and puzzles, checkmates, or finished matches with at least 10 half-moves, count toward the streak. Five-minute quick matches count too.",
    "Cuentan lecciones, problemas, mates y partidas terminadas con al menos 10 medias jugadas, incluidas las partidas rápidas de cinco minutos.",
    "Les leçons, problèmes, mats et parties terminées d’au moins 10 demi-coups comptent, y compris les parties rapides de cinq minutes.",
    "تُحسب الدروس والألغاز المكتملة ومباريات المات والمباريات المنتهية بعد 10 أنصاف نقلات على الأقل، بما فيها مباريات الخمس دقائق.",
    "Abgeschlossene Lektionen, Aufgaben, Schachmatts und beendete Partien mit mindestens 10 Halbzügen zählen, auch Fünf-Minuten-Partien.",
  ],
});

ChessText.extend({
  settings: [
    "Ayarlar",
    "Settings",
    "Ajustes",
    "Réglages",
    "الإعدادات",
    "Einstellungen",
  ],
  languageLabel: ["Dil", "Language", "Idioma", "Langue", "اللغة", "Sprache"],
  mateGoal: [
    "Şah mat",
    "Checkmate",
    "Jaque mate",
    "Échec et mat",
    "كش مات",
    "Schachmatt",
  ],
  gainGoal: [
    "Taş kazan",
    "Win material",
    "Gana material",
    "Gagnez du matériel",
    "اكسب قطعة",
    "Material gewinnen",
  ],
  promoteGoal: [
    "Piyonu terfi ettir",
    "Promote a pawn",
    "Corona un peón",
    "Promouvez un pion",
    "رقِّ بيدقًا",
    "Bauern umwandeln",
  ],
  castleGoal: [
    "Şahı güvene al: rok",
    "Castle your king",
    "Enroca",
    "Faites le roque",
    "قم بالتبييت",
    "Rochieren",
  ],
  targetMoves: [
    "Hedef hamle",
    "Target moves",
    "Jugadas objetivo",
    "Coups visés",
    "النقلات المستهدفة",
    "Zielzüge",
  ],
  usedMoves: ["Hamle", "Moves", "Jugadas", "Coups", "النقلات", "Züge"],
  gainDetail: [
    "En az {n} puanlık net taş üstünlüğü kazan.",
    "Gain at least {n} points of net material.",
    "Gana al menos {n} puntos netos de material.",
    "Gagnez au moins {n} points nets de matériel.",
    "اكسب تفوقًا ماديًا صافيًا قدره {n} نقاط.",
    "Gewinne netto mindestens {n} Materialpunkte.",
  ],
  freePuzzle: [
    "Hedefi aşsan da devam edebilirsin.",
    "You can continue beyond the target.",
    "Puedes continuar tras superar el objetivo.",
    "Vous pouvez continuer au-delà de l’objectif.",
    "يمكنك الاستمرار بعد تجاوز الهدف.",
    "Du kannst über das Ziel hinaus weiterspielen.",
  ],
  puzzleEnded: [
    "Konum sona erdi. Yeniden dene.",
    "The position has ended. Try again.",
    "La posición terminó. Inténtalo de nuevo.",
    "La position est terminée. Réessayez.",
    "انتهى الموقف. حاول مجددًا.",
    "Die Stellung ist beendet. Versuche es erneut.",
  ],
  undoPuzzle: [
    "Hamleyi geri al",
    "Undo move",
    "Deshacer jugada",
    "Annuler le coup",
    "تراجع عن النقلة",
    "Zug zurücknehmen",
  ],
});

ChessText.extend({
  nightMode: [
    "Gece modu",
    "Night mode",
    "Modo nocturno",
    "Mode nuit",
    "الوضع الليلي",
    "Nachtmodus",
  ],
  mountains: [
    "Geometrik",
    "Facets",
    "Facetas",
    "Facettes",
    "أشكال هندسية",
    "Facetten",
  ],
  arches: ["Çizgiler", "Lines", "Líneas", "Lignes", "خطوط", "Linien"],
  stars: ["Akşam", "Dusk", "Atardecer", "Crépuscule", "الغسق", "Abend"],
});
