"use strict";
const ChessLessons = [
  {
    name: "p",
    piece: "P",
    fen: "7k/8/8/8/8/8/4P3/K7 w - - 0 1",
    move: "e2e4",
    text: [
      "Piyon ileri gider. İlk hamlesinde iki kare ilerleyebilir. e2’deki piyonu e4’e götür.",
      "Pawns move forward. On their first move they may advance two squares. Move the pawn from e2 to e4.",
      "El peón avanza. En su primer movimiento puede avanzar dos casillas. Lleva el peón de e2 a e4.",
      "Le pion avance. À son premier coup, il peut avancer de deux cases. Déplacez le pion de e2 à e4.",
      "يتقدم البيدق للأمام، ويمكنه التقدم مربعين في نقلته الأولى. حرّك البيدق من e2 إلى e4.",
      "Bauern ziehen vorwärts. Beim ersten Zug dürfen sie zwei Felder ziehen. Ziehe den Bauern von e2 nach e4.",
    ],
  },
  {
    name: "p",
    piece: "P",
    fen: "7k/8/3p4/4P3/8/8/8/K7 w - - 0 1",
    move: "e5d6",
    text: [
      "Piyon çaprazındaki taşı alır. e5’teki piyonla d6’daki piyonu al.",
      "Pawns capture diagonally. Use the pawn on e5 to capture the pawn on d6.",
      "Los peones capturan en diagonal. Con el peón de e5 captura el de d6.",
      "Le pion prend en diagonale. Prenez le pion d6 avec celui de e5.",
      "يأخذ البيدق قطريًا. خذ بيدق d6 ببيدق e5.",
      "Bauern schlagen diagonal. Schlage mit dem Bauern e5 den Bauern auf d6.",
    ],
  },
  {
    name: "r",
    piece: "R",
    fen: "7k/8/8/8/3R4/8/8/K7 w - - 0 1",
    move: "d4d7",
    text: [
      "Kale yatay ve dikey ilerler. Taşların üzerinden atlayamaz. Kaleyi d7’ye götür.",
      "Rooks move along ranks and files. They cannot jump over pieces. Move the rook to d7.",
      "La torre se mueve por filas y columnas, sin saltar piezas. Muévela a d7.",
      "La tour suit les lignes et colonnes sans sauter les pièces. Jouez la tour en d7.",
      "يتحرك الرخ أفقيًا وعموديًا دون القفز فوق القطع. حرّكه إلى d7.",
      "Türme ziehen waagerecht und senkrecht, ohne Figuren zu überspringen. Ziehe den Turm nach d7.",
    ],
  },
  {
    name: "b",
    piece: "B",
    fen: "8/7k/8/8/3B4/8/8/K7 w - - 0 1",
    move: "d4g7",
    text: [
      "Fil çapraz ilerler; hep aynı renk karelerde kalır. Fili g7’ye götür.",
      "Bishops move diagonally and stay on the same square color. Move the bishop to g7.",
      "El alfil se mueve en diagonal y permanece en el mismo color. Muévelo a g7.",
      "Le fou suit les diagonales et reste sur une même couleur. Jouez le fou en g7.",
      "يتحرك الفيل قطريًا ويبقى على لون واحد. حرّكه إلى g7.",
      "Läufer ziehen diagonal und bleiben auf derselben Feldfarbe. Ziehe den Läufer nach g7.",
    ],
  },
  {
    name: "n",
    piece: "N",
    fen: "7k/8/8/8/3N4/3PP3/8/K7 w - - 0 1",
    move: "d4f5",
    text: [
      "At iki kare bir yönde, bir kare yana gider. Taşların üzerinden atlayabilir. Atı f5’e götür.",
      "Knights move two squares one way and one sideways. They can jump over pieces. Move the knight to f5.",
      "El caballo avanza dos casillas y una lateral. Puede saltar piezas. Muévelo a f5.",
      "Le cavalier avance de deux cases puis une de côté. Il peut sauter les pièces. Jouez en f5.",
      "يتحرك الحصان مربعين في اتجاه ومربعًا جانبيًا، ويمكنه القفز فوق القطع. حرّكه إلى f5.",
      "Springer ziehen zwei Felder in eine Richtung und eines seitwärts. Sie können Figuren überspringen. Ziehe nach f5.",
    ],
  },
  {
    name: "q",
    piece: "Q",
    fen: "8/7k/8/8/3Q4/8/8/K7 w - - 0 1",
    move: "d4g4",
    text: [
      "Vezir yatay, dikey ve çapraz ilerler. Veziri g4’e götür.",
      "Queens move along ranks, files and diagonals. Move the queen to g4.",
      "La dama se mueve en horizontal, vertical y diagonal. Muévela a g4.",
      "La dame suit les lignes, colonnes et diagonales. Jouez la dame en g4.",
      "يتحرك الوزير أفقيًا وعموديًا وقطريًا. حرّكه إلى g4.",
      "Die Dame zieht waagerecht, senkrecht und diagonal. Ziehe sie nach g4.",
    ],
  },
  {
    name: "k",
    piece: "K",
    fen: "7k/8/8/8/3K4/8/8/8 w - - 0 1",
    move: "d4e5",
    text: [
      "Şah her yönde bir kare gider. Tehdit altındaki kareye gidemez. Şahı e5’e götür.",
      "Kings move one square in any direction, but never into attack. Move the king to e5.",
      "El rey se mueve una casilla en cualquier dirección, sin entrar en jaque. Muévelo a e5.",
      "Le roi avance d’une case dans toute direction, sans se mettre en échec. Jouez en e5.",
      "يتحرك الملك مربعًا واحدًا في أي اتجاه، ولا يدخل مربعًا مهددًا. حرّكه إلى e5.",
      "Der König zieht ein Feld in jede Richtung, aber nie auf ein bedrohtes Feld. Ziehe nach e5.",
    ],
  },
  {
    name: "check",
    piece: "K",
    fen: "4r2k/8/8/8/8/8/8/4K3 w - - 0 1",
    move: "e1d1",
    text: [
      "Şahtayken tehdidi gidermelisin: şahı kaçır, araya taş koy veya saldıranı al. Şahı d1’e kaçır.",
      "In check, escape, block the attack or capture the attacker. Move the king to d1.",
      "En jaque, escapa, bloquea o captura al atacante. Lleva el rey a d1.",
      "En échec, fuyez, bloquez ou prenez l’attaquant. Déplacez le roi en d1.",
      "عند الكش، ابتعد أو احجب الهجوم أو خذ المهاجم. حرّك الملك إلى d1.",
      "Im Schach musst du ausweichen, blockieren oder den Angreifer schlagen. Ziehe den König nach d1.",
    ],
  },
  {
    name: "castling",
    piece: "R",
    fen: "4k3/8/8/8/8/8/8/4K2R w K - 0 1",
    move: "e1g1",
    text: [
      "Rokta şah iki kare gider, kale yanına geçer. İkisi de oynamamış olmalı; araları boş, şahın yolu tehditsiz olmalı. Şahı g1’e götür.",
      "To castle, the king moves two squares and the rook crosses beside it. Neither may have moved; the path must be clear and the king’s path safe. Move the king to g1.",
      "Al enrocar, el rey avanza dos casillas y la torre pasa a su lado. Ninguno debe haberse movido; el camino debe estar libre y el del rey sin amenazas. Mueve el rey a g1.",
      "Au roque, le roi avance de deux cases et la tour passe à côté. Aucun ne doit avoir bougé ; le passage doit être libre et sûr pour le roi. Jouez le roi en g1.",
      "في التبييت يتحرك الملك مربعين ويعبر الرخ بجانبه. يجب ألا يكونا قد تحركا، وأن يخلو الطريق من القطع والتهديد للملك. حرّك الملك إلى g1.",
      "Bei der Rochade zieht der König zwei Felder und der Turm daneben. Beide dürfen noch nicht gezogen haben; der Weg muss frei und für den König sicher sein. Ziehe nach g1.",
    ],
  },
  {
    name: "ep",
    piece: "P",
    fen: "7k/8/8/3pP3/8/8/8/K7 w - d6 0 1",
    move: "e5d6",
    text: [
      "Siyah piyon d7’den d5’e iki kare geldi. Yalnızca hemen sonraki hamlede, onu d6’da yakalayabilirsin. e5–d6 oyna.",
      "Black just moved d7–d5. On this move only, capture that pawn as if it were on d6. Play e5–d6.",
      "Las negras acaban de jugar d7–d5. Solo ahora puedes capturar ese peón como si estuviera en d6. Juega e5–d6.",
      "Les noirs viennent de jouer d7–d5. À ce coup seulement, prenez ce pion comme s’il était en d6. Jouez e5–d6.",
      "لعب الأسود للتو d7–d5. في هذه النقلة فقط يمكنك أخذ البيدق كأنه في d6. العب e5–d6.",
      "Schwarz hat gerade d7–d5 gezogen. Nur jetzt darfst du den Bauern schlagen, als stünde er auf d6. Spiele e5–d6.",
    ],
  },
  {
    name: "promote",
    piece: "Q",
    fen: "7k/4P3/8/8/8/8/8/K7 w - - 0 1",
    move: "e7e8q",
    text: [
      "Son sıraya ulaşan piyon vezir, kale, fil veya ata dönüşür. e8’e ilerle ve veziri seç.",
      "A pawn on the last rank becomes a queen, rook, bishop or knight. Advance to e8 and choose the queen.",
      "Un peón en la última fila se convierte en dama, torre, alfil o caballo. Avanza a e8 y elige dama.",
      "Sur la dernière rangée, le pion devient dame, tour, fou ou cavalier. Avancez en e8 et choisissez la dame.",
      "يتحول البيدق في الصف الأخير إلى وزير أو رخ أو فيل أو حصان. تقدم إلى e8 واختر الوزير.",
      "Auf der letzten Reihe wird ein Bauer zur Dame, zum Turm, Läufer oder Springer. Ziehe nach e8 und wähle die Dame.",
    ],
  },
  {
    name: "mate",
    piece: "Q",
    fen: "7k/8/5KQ1/8/8/8/8/8 w - - 0 1",
    move: "g6g7",
    text: [
      "Şah tehdit altında ve hiçbir yasal kurtuluş yoksa mat olur. Veziri g7’ye götürerek mat et.",
      "Check with no legal escape is checkmate. Move the queen to g7 to deliver mate.",
      "El jaque sin escape legal es mate. Mueve la dama a g7 para dar mate.",
      "Un échec sans issue légale est mat. Jouez la dame en g7 pour mater.",
      "الكش بلا مخرج قانوني هو كش مات. حرّك الوزير إلى g7 لتحقيق المات.",
      "Schach ohne legalen Ausweg ist Schachmatt. Setze mit der Dame auf g7 matt.",
    ],
  },
];
