"use strict";
const ChessOpponents = [
  {
    name: "Deniz Aral",
    code: "TR",
    strength: 1,
    style: "balanced",
    reward: 60,
  },
  {
    name: "Lucía Vega",
    code: "ES",
    strength: 2,
    style: "attacking",
    reward: 120,
  },
  {
    name: "Émile Laurent",
    code: "FR",
    strength: 3,
    style: "positional",
    reward: 180,
  },
  {
    name: "Mila Orlova",
    code: "RU",
    strength: 4,
    style: "defensive",
    reward: 240,
  },
  {
    name: "Viktor Belov",
    code: "RU",
    strength: 5,
    style: "balanced",
    reward: 300,
  },
  {
    name: "Ece Yalın",
    code: "TR",
    strength: 2,
    style: "positional",
    reward: 130,
  },
  {
    name: "Mateo Soler",
    code: "ES",
    strength: 3,
    style: "attacking",
    reward: 190,
  },
  {
    name: "Léon Moreau",
    code: "FR",
    strength: 3,
    style: "defensive",
    reward: 190,
  },
  {
    name: "Alina Sokolova",
    code: "RU",
    strength: 4,
    style: "attacking",
    reward: 260,
  },
  {
    name: "Felix Adler",
    code: "DE",
    strength: 4,
    style: "positional",
    reward: 260,
  },
  {
    name: "Selim Kaya",
    code: "TR",
    strength: 5,
    style: "defensive",
    reward: 320,
  },
  {
    name: "Inés Navarro",
    code: "ES",
    strength: 5,
    style: "attacking",
    reward: 340,
  },
];
