"use strict";
const ChessText = (() => {
  const languages = ["tr", "en", "es", "fr", "ar", "de"];
  const rows = {
    victory: ["Galibiyet", "Victory", "Victoria", "Victoire", "فوز", "Sieg"],
    defeat: [
      "Mağlubiyet",
      "Defeat",
      "Derrota",
      "Défaite",
      "خسارة",
      "Niederlage",
    ],
    inspect: [
      "Tahtayı incele",
      "View board",
      "Ver tablero",
      "Voir l’échiquier",
      "عرض الرقعة",
      "Brett ansehen",
    ],
    winner: ["Kazanan", "Winner", "Ganador", "Vainqueur", "الفائز", "Sieger"],

    result: ["Sonuç", "Result", "Resultado", "Résultat", "النتيجة", "Ergebnis"],
    pause: ["Duraklat", "Pause", "Pausar", "Pause", "إيقاف مؤقت", "Pause"],
    newGame: [
      "Yeni oyun",
      "New game",
      "Nueva partida",
      "Nouvelle partie",
      "مباراة جديدة",
      "Neue Partie",
    ],
    mainMenu: [
      "Ana menü",
      "Main menu",
      "Menú principal",
      "Menu principal",
      "القائمة الرئيسية",
      "Hauptmenü",
    ],
    on: ["Açık", "On", "Sí", "Activé", "مفعّل", "An"],
    off: ["Kapalı", "Off", "No", "Désactivé", "معطّل", "Aus"],
    night: ["Gece", "Night", "Noche", "Nuit", "ليلي", "Nacht"],
    day: ["Gündüz", "Day", "Día", "Jour", "نهاري", "Tag"],

    title: ["Satranç", "Chess", "Ajedrez", "Échecs", "الشطرنج", "Schach"],
    solo: [
      "Tek oyuncu",
      "Solo play",
      "Un jugador",
      "Solo",
      "لاعب واحد",
      "Einzelspieler",
    ],
    local: [
      "İki oyuncu",
      "Two players",
      "Dos jugadores",
      "Deux joueurs",
      "لاعبان",
      "Zwei Spieler",
    ],
    academy: [
      "Satranç okulu",
      "Chess school",
      "Escuela de ajedrez",
      "École d’échecs",
      "مدرسة الشطرنج",
      "Schachschule",
    ],
    resume: [
      "Devam et",
      "Continue",
      "Continuar",
      "Continuer",
      "متابعة",
      "Fortsetzen",
    ],
    play: ["Oyna", "Play", "Jugar", "Jouer", "العب", "Spielen"],
    back: ["Geri", "Back", "Volver", "Retour", "رجوع", "Zurück"],
    menu: ["Menü", "Menu", "Menú", "Menu", "القائمة", "Menü"],
    opponent: [
      "Rakip seç",
      "Choose opponent",
      "Elige rival",
      "Choisir un adversaire",
      "اختر منافسًا",
      "Gegner wählen",
    ],
    settings: [
      "Oyun ayarları",
      "Game settings",
      "Ajustes de partida",
      "Réglages de partie",
      "إعدادات المباراة",
      "Spieleinstellungen",
    ],
    white: ["Beyaz", "White", "Blancas", "Blancs", "الأبيض", "Weiß"],
    black: ["Siyah", "Black", "Negras", "Noirs", "الأسود", "Schwarz"],
    random: [
      "Rastgele",
      "Random",
      "Aleatorio",
      "Aléatoire",
      "عشوائي",
      "Zufällig",
    ],
    color: [
      "Taşların",
      "Your pieces",
      "Tus piezas",
      "Vos pièces",
      "قطعك",
      "Deine Figuren",
    ],
    time: ["Süre", "Time", "Tiempo", "Cadence", "الوقت", "Bedenkzeit"],
    unlimited: [
      "Süresiz",
      "Untimed",
      "Sin reloj",
      "Sans horloge",
      "بلا توقيت",
      "Ohne Uhr",
    ],
    minutes: ["dk", "min", "min", "min", "د", "Min."],
    turn: ["Hamle sırası", "To move", "Turno", "Au trait", "الدور", "Am Zug"],
    thinking: [
      "Düşünüyor",
      "Thinking",
      "Pensando",
      "Réflexion",
      "يفكر",
      "Überlegt",
    ],
    check: ["Şah", "Check", "Jaque", "Échec", "كش", "Schach"],
    mate: [
      "Şah mat",
      "Checkmate",
      "Jaque mate",
      "Échec et mat",
      "كش مات",
      "Schachmatt",
    ],
    stalemate: ["Pat", "Stalemate", "Ahogado", "Pat", "تعادل بالخنق", "Patt"],
    material: [
      "Mat mümkün değil",
      "No possible mate",
      "Mate imposible",
      "Mat impossible",
      "لا يمكن تحقيق مات",
      "Kein Matt möglich",
    ],
    seventyfive: [
      "75 hamle kuralı",
      "75-move rule",
      "Regla de 75 movimientos",
      "Règle des 75 coups",
      "قاعدة 75 نقلة",
      "75-Züge-Regel",
    ],
    fivefold: [
      "Beş kez tekrar",
      "Fivefold repetition",
      "Quíntuple repetición",
      "Quintuple répétition",
      "تكرار خمس مرات",
      "Fünffache Wiederholung",
    ],
    claimed: [
      "Beraberlik talebi",
      "Draw claimed",
      "Tablas reclamadas",
      "Nulle réclamée",
      "طلب التعادل",
      "Remis beansprucht",
    ],
    agreed: [
      "Anlaşmalı beraberlik",
      "Draw by agreement",
      "Tablas acordadas",
      "Nulle par accord",
      "تعادل بالاتفاق",
      "Remis vereinbart",
    ],
    timeout: [
      "Süre doldu",
      "Time expired",
      "Tiempo agotado",
      "Temps écoulé",
      "انتهى الوقت",
      "Zeit abgelaufen",
    ],
    resigned: [
      "Oyun terk edildi",
      "Resignation",
      "Abandono",
      "Abandon",
      "استسلام",
      "Aufgabe",
    ],
    draw: ["Berabere", "Draw", "Tablas", "Nulle", "تعادل", "Remis"],
    wins: ["kazandı", "wins", "gana", "gagnent", "يفوز", "gewinnt"],
    rematch: [
      "Yeniden oyna",
      "Play again",
      "Volver a jugar",
      "Rejouer",
      "العب مجددًا",
      "Erneut spielen",
    ],
    moves: ["Hamleler", "Moves", "Jugadas", "Coups", "النقلات", "Züge"],
    flip: [
      "Tahtayı çevir",
      "Flip board",
      "Girar tablero",
      "Tourner l’échiquier",
      "اقلب الرقعة",
      "Brett drehen",
    ],
    resign: [
      "Terk et",
      "Resign",
      "Abandonar",
      "Abandonner",
      "استسلام",
      "Aufgeben",
    ],
    resignAsk: [
      "Oyunu terk et?",
      "Resign this game?",
      "¿Abandonar la partida?",
      "Abandonner la partie ?",
      "هل تستسلم؟",
      "Partie aufgeben?",
    ],
    cancel: ["Vazgeç", "Cancel", "Cancelar", "Annuler", "إلغاء", "Abbrechen"],
    confirm: [
      "Onayla",
      "Confirm",
      "Confirmar",
      "Confirmer",
      "تأكيد",
      "Bestätigen",
    ],
    newAsk: [
      "Yeni oyun mevcut oyunun yerini alacak.",
      "A new game will replace this game.",
      "La nueva partida reemplazará la actual.",
      "La nouvelle partie remplacera la partie en cours.",
      "ستحل المباراة الجديدة محل الحالية.",
      "Die neue Partie ersetzt die aktuelle.",
    ],
    promote: [
      "Terfi",
      "Promotion",
      "Promoción",
      "Promotion",
      "ترقية",
      "Umwandlung",
    ],
    claim: [
      "Beraberlik talep et",
      "Claim draw",
      "Reclamar tablas",
      "Réclamer la nulle",
      "اطلب التعادل",
      "Remis beanspruchen",
    ],
    offer: [
      "Beraberlik öner",
      "Offer draw",
      "Ofrecer tablas",
      "Proposer la nulle",
      "اعرض التعادل",
      "Remis anbieten",
    ],
    offerAsk: [
      "Beraberliği kabul ediyor musun?",
      "Accept the draw?",
      "¿Aceptar tablas?",
      "Accepter la nulle ?",
      "هل تقبل التعادل؟",
      "Remis annehmen?",
    ],
    lesson: ["Ders", "Lesson", "Lección", "Leçon", "درس", "Lektion"],
    completed: [
      "Tamamlandı",
      "Completed",
      "Completado",
      "Terminé",
      "مكتمل",
      "Abgeschlossen",
    ],
    next: [
      "Sonraki ders",
      "Next lesson",
      "Siguiente lección",
      "Leçon suivante",
      "الدرس التالي",
      "Nächste Lektion",
    ],
    retry: [
      "Tekrar dene",
      "Try again",
      "Reintentar",
      "Réessayer",
      "حاول مجددًا",
      "Erneut versuchen",
    ],
    hint: [
      "Göster",
      "Show move",
      "Mostrar jugada",
      "Voir le coup",
      "أظهر النقلة",
      "Zug zeigen",
    ],
    correct: [
      "Doğru hamle",
      "Correct move",
      "Jugada correcta",
      "Bon coup",
      "نقلة صحيحة",
      "Richtiger Zug",
    ],
    tryTarget: [
      "İşaretli kareye ulaş.",
      "Reach the marked square.",
      "Llega a la casilla marcada.",
      "Atteignez la case marquée.",
      "صل إلى المربع المحدد.",
      "Erreiche das markierte Feld.",
    ],
    progress: [
      "ders tamamlandı",
      "lessons completed",
      "lecciones completadas",
      "leçons terminées",
      "دروس مكتملة",
      "Lektionen abgeschlossen",
    ],
    sound: ["Ses", "Sound", "Sonido", "Son", "الصوت", "Ton"],
    theme: ["Görünüm", "Theme", "Tema", "Thème", "المظهر", "Darstellung"],
    board: [
      "Satranç tahtası",
      "Chessboard",
      "Tablero",
      "Échiquier",
      "رقعة الشطرنج",
      "Schachbrett",
    ],
    close: ["Kapat", "Close", "Cerrar", "Fermer", "إغلاق", "Schließen"],
    paused: [
      "Duraklatıldı",
      "Paused",
      "En pausa",
      "En pause",
      "متوقف مؤقتًا",
      "Pausiert",
    ],
    pausedNote: [
      "Menüde ve uygulama arka plandayken saatler durur.",
      "Clocks pause in menus and while the app is in the background.",
      "El reloj se pausa en los menús y en segundo plano.",
      "Les horloges s’arrêtent dans les menus et en arrière-plan.",
      "تتوقف الساعات في القوائم وعندما يكون التطبيق في الخلفية.",
      "Die Uhren pausieren in Menüs und im Hintergrund.",
    ],
    sameDevice: [
      "Aynı cihazda",
      "On this device",
      "En este dispositivo",
      "Sur cet appareil",
      "على هذا الجهاز",
      "Auf diesem Gerät",
    ],
    p: ["Piyon", "Pawn", "Peón", "Pion", "بيدق", "Bauer"],
    n: ["At", "Knight", "Caballo", "Cavalier", "حصان", "Springer"],
    b: ["Fil", "Bishop", "Alfil", "Fou", "فيل", "Läufer"],
    r: ["Kale", "Rook", "Torre", "Tour", "رخ", "Turm"],
    q: ["Vezir", "Queen", "Dama", "Dame", "وزير", "Dame"],
    k: ["Şah", "King", "Rey", "Roi", "ملك", "König"],
    castling: ["Rok", "Castling", "Enroque", "Roque", "التبييت", "Rochade"],
    ep: [
      "Geçerken alma",
      "En passant",
      "Captura al paso",
      "Prise en passant",
      "الأخذ بالتجاوز",
      "En passant",
    ],
    rules: ["Kurallar", "Rules", "Reglas", "Règles", "القواعد", "Regeln"],
    drawRules: [
      "Pat ve matın mümkün olmadığı konumlar beraberedir. Üç tekrar veya 50 hamlede talep edebilirsin; beş tekrar veya 75 hamlede oyun otomatik biter. Piyon hamlesi ve taş alma sayacı sıfırlar.",
      "Stalemate and positions where mate is impossible are drawn. Claim after three repetitions or 50 moves; five repetitions or 75 moves end the game automatically. Pawn moves and captures reset the counter.",
      "El ahogado y el mate imposible son tablas. Reclama tras tres repeticiones o 50 movimientos; cinco repeticiones o 75 movimientos terminan automáticamente. Mover un peón o capturar reinicia el contador.",
      "Le pat et le mat impossible donnent la nulle. Réclamez après trois répétitions ou 50 coups ; cinq répétitions ou 75 coups terminent automatiquement. Un coup de pion ou une prise remet le compteur à zéro.",
      "الخنق واستحالة المات تعادل. اطلب التعادل بعد ثلاثة تكرارات أو 50 نقلة؛ خمسة تكرارات أو 75 نقلة تنهي المباراة تلقائيًا. تحريك بيدق أو أخذ قطعة يصفر العداد.",
      "Patt und unmögliches Matt sind remis. Nach dreifacher Wiederholung oder 50 Zügen kann Remis beansprucht werden; nach fünf Wiederholungen oder 75 Zügen endet die Partie automatisch. Bauernzüge und Schlagen setzen den Zähler zurück.",
    ],
  };
  const t = (key, lang = "tr") => rows[key]?.[languages.indexOf(lang)] ?? key;
  return {
    languages,
    t,
    extend(values) {
      Object.assign(rows, values);
    },
  };
})();
