"use strict";
// hand-drawn sprites
(function (YB) {
  const SUIT_SMALL = {
    H: [".##.##.", "#######", "#######", "#######", ".#####.", "..###..", "...#..."],
    D: ["...#...", "..###..", ".#####.", "#######", ".#####.", "..###..", "...#..."],
    C: ["..###..", "..###..", "##.#.##", "#######", "##.#.##", "...#...", "..###.."],
    S: ["...#...", "..###..", ".#####.", "#######", "#######", "##.#.##", "..###.."],
  };

  const SUIT_BIG = {
    H: [
      "..###...###..",
      ".##ww#.#####.",
      "##ww#########",
      "##w##########",
      "#############",
      "#############",
      ".###########.",
      "..#########..",
      "...#######...",
      "....#####....",
      ".....###.....",
      "......#......",
    ],
    D: [
      "......#......",
      ".....###.....",
      "....#w###....",
      "...#ww####...",
      "..#w#######..",
      ".###########.",
      "#############",
      ".###########.",
      "..#########..",
      "...#######...",
      "....#####....",
      ".....###.....",
      "......#......",
    ],
    C: [
      ".....###.....",
      "....#w###....",
      "....#####....",
      "....#####....",
      ".###.###.###.",
      "#w###.#.#####",
      "#############",
      "#####.#.#####",
      ".###..#..###.",
      "......#......",
      ".....###.....",
      "....#####....",
    ],
    S: [
      "......#......",
      ".....###.....",
      "....#w###....",
      "...#ww####...",
      "..#w#######..",
      ".###########.",
      "#############",
      "#############",
      ".####.#.####.",
      "......#......",
      ".....###.....",
      "....#####....",
    ],
  };

  const FACES = {
    13: [
      "...y...y...y...",
      "...yy.yyy.yy...",
      "...yyyyyyyyy...",
      "...YrYYbYYrY...",
      "...hhhhhhhhh...",
      "..hhkhhhhhkhh..",
      "..hhhhhHhhhhh..",
      "..nhhhhHhhhhn..",
      "..nnhhRRRhhnn..",
      "...nnnhhhnnn...",
      "....nnnnnnn....",
      "..www.nnn.www..",
      ".rrwwwwwwwwwrr.",
      "rrrrrrryrrrrrrr",
      "rrRrrryyyrrrRrr",
      "rrRrrrryrrrrRrr",
      "rrRrrrrrrrrrRrr",
    ],
    12: [
      "....y..y..y....",
      "....yyyyyyy....",
      "....YpYYYpY....",
      "..yyhhhhhhhyy..",
      ".yyhhkhhhkhhyy.",
      ".yyhhhhhhhhhyy.",
      ".yyhphhHhhphyy.",
      ".yyhhhhhhhhhyy.",
      ".yYyhhhRhhhyYy.",
      ".yY.yhhhhhy.Yy.",
      ".Y...hhhhh...Y.",
      "..bbbbwwwbbbb..",
      ".bbbbbbwbbbbbb.",
      "bbBbbbbybbbbBbb",
      "bbBbbbyyybbbBbb",
      "bbBbbbbybbbbBbb",
      "bbBbbbbbbbbbBbb",
    ],
    11: [
      "..........z....",
      ".........zz....",
      "...llllllz.....",
      "..lllllllll....",
      ".LLLLLLLLLLL...",
      "..nhhhhhhhn....",
      "..nhkhhhkhn....",
      "..nhhhhhhhn....",
      "..nhhhHhhhn....",
      "...hhhRhhh.....",
      "....hhhhh......",
      "..ooowwwooo....",
      ".oooooyoooooo..",
      "ooOoooyooooOoo.",
      "ooOoooyooooOoo.",
      "ooOooooooooOoo.",
      "ooOooooooooOoo.",
    ],
  };

  // the innkeeper who runs the table: a fez, a moustache and a full mug
  const HOST = {
    idle: [
      "...........kk.....................",
      ".........rrrrrrk..................",
      ".........rrrrrrrk.................",
      "........rorrrrrRkk................",
      "........RRRRRRRRkk................",
      ".......hwwhhhhhhhkh...............",
      "......hwhhhhhhhhhhhh..............",
      ".....hhhhhhhhhhhhhhhh.............",
      "....nhhhhhhhhhhhhhhhhn............",
      "...nnhNNNhhhhhhhhNNNhnn.....ssss..",
      "...nhhhhhhhhhhhhhhhhhhn....swssss.",
      "...HhhhwkhhhhhhhhwkhhhH....ttttTT.",
      "...HhhhkkhhhhhhhhkkhhhH...hMMMMMM.",
      "...HxxhhhhhhpphhhhhhxxH...hhtttTT.",
      "...HxxhhhhhpppphhhhhxxH...hhtttTT.",
      "NN..hhhhhhhpPPphhhhhhh..NN.MMMMMM.",
      ".NN.hhNNNNNNPPNNNNNNhh.NN..ttttTT.",
      "..NNNNNNNNNNNNNNNNNNNNNN..hh......",
      "...NNNNNNhhhhhhhhNNNNNN..sss......",
      "......hRRRRRRRRRRRRh....sss.......",
      ".......hhhhhhhhhhhh....sss........",
      "......sssTssssssTsss..sss.........",
      ".....ssssTssssssTssss.............",
      "....sssssTSSSSSSTsssss............",
      "...ssssssTSSSSSSTssssss...........",
    ],
    blink: [
      "...........kk.....................",
      ".........rrrrrrk..................",
      ".........rrrrrrrk.................",
      "........rorrrrrRkk................",
      "........RRRRRRRRkk................",
      ".......hwwhhhhhhhkh...............",
      "......hwhhhhhhhhhhhh..............",
      ".....hhhhhhhhhhhhhhhh.............",
      "....nhhhhhhhhhhhhhhhhn............",
      "...nnhNNNhhhhhhhhNNNhnn.....ssss..",
      "...nhhhhhhhhhhhhhhhhhhn....swssss.",
      "...HhhhhhhhhhhhhhhhhhhH....ttttTT.",
      "...HhhhkkhhhhhhhhkkhhhH...hMMMMMM.",
      "...HxxhhhhhhpphhhhhhxxH...hhtttTT.",
      "...HxxhhhhhpppphhhhhxxH...hhtttTT.",
      "NN..hhhhhhhpPPphhhhhhh..NN.MMMMMM.",
      ".NN.hhNNNNNNPPNNNNNNhh.NN..ttttTT.",
      "..NNNNNNNNNNNNNNNNNNNNNN..hh......",
      "...NNNNNNhhhhhhhhNNNNNN..sss......",
      "......hRRRRRRRRRRRRh....sss.......",
      ".......hhhhhhhhhhhh....sss........",
      "......sssTssssssTsss..sss.........",
      ".....ssssTssssssTssss.............",
      "....sssssTSSSSSSTsssss............",
      "...ssssssTSSSSSSTssssss...........",
    ],
    cheer: [
      "...........kk.....................",
      ".........rrrrrrk..................",
      ".........rrrrrrrk.................",
      "........rorrrrrRkk................",
      "........RRRRRRRRkk................",
      ".......hwwhhhhhhhkh...............",
      "......hwhhhhhhhhhhhh..............",
      ".....hhhhhhhhhhhhhhhh........s....",
      "....nhhhhhhhhhhhhhhhhn.....s.ss...",
      "...nnhNNNhhhhhhhhNNNhnn.....ssss..",
      "...nhhhhhhhhhhhhhhhhhhn....swssss.",
      "...HhhhkkhhhhhhhhkkhhhH....ttttTT.",
      "...HhhkhhkhhhhhhkhhkhhH...hMMMMMM.",
      "...HxxhhhhhhpphhhhhhxxH...hhtttTT.",
      "...HxxhhhhhpppphhhhhxxH...hhtttTT.",
      "NN..hhhhhhhpPPphhhhhhh..NN.MMMMMM.",
      ".NN.hhNNNNNNPPNNNNNNhh.NN..ttttTT.",
      "..NNNNNNNNNNNNNNNNNNNNNN..hh......",
      "...NNNNNNhhhhhhhhNNNNNN..sss......",
      "......hRwwwwwwwwwwRh....sss.......",
      ".......hRppppppppRh....sss........",
      "......sssTssssssTsss..sss.........",
      ".....ssssTssssssTssss.............",
      "....sssssTSSSSSSTsssss............",
      "...ssssssTSSSSSSTssssss...........",
    ],
    sad: [
      "...........kk.....................",
      ".........rrrrrrk..................",
      ".........rrrrrrrk.................",
      "........rorrrrrRkk................",
      "........RRRRRRRRkk................",
      ".......hwwhhhhhhhkh...............",
      "......hwhhhhhhhhhhhhc.............",
      ".....hhhhhhhhhhhhhhhcc............",
      "....nhhhhhhhhhhhhhhhhn............",
      "...nnhhhNNNhhhhNNNhhhnn.....ssss..",
      "...nhhhhhhhhhhhhhhhhhhn....swssss.",
      "...HhhhwkhhhhhhhhwkhhhH....ttttTT.",
      "...HhhhkkhhhhhhhhkkhhhH...hMMMMMM.",
      "...HxxhhhhhhpphhhhhhxxH...hhtttTT.",
      "...HxxhhhhhpppphhhhhxxH...hhtttTT.",
      "NN..hhhhhhhpPPphhhhhhh..NN.MMMMMM.",
      ".NN.hhNNNNNNPPNNNNNNhh.NN..ttttTT.",
      "..NNNNNNNNNNNNNNNNNNNNNN..hh......",
      "...NNNNNNhhhhhhhhNNNNNN..sss......",
      "......hhhhhRRRRhhhhh....sss.......",
      ".......hhRhhhhhhRhh....sss........",
      "......sssTssssssTsss..sss.........",
      ".....ssssTssssssTssss.............",
      "....sssssTSSSSSSTsssss............",
      "...ssssssTSSSSSSTssssss...........",
    ],
  };

  const host = (mood) => HOST[mood] || HOST.idle;

  // art for the special cards, 15 pixels wide
  const SPECIAL_ART = {
    joker: [
      ".....ssss......",
      "....ssssss.....",
      "....sSssSs.....",
      "....ssssss.....",
      "...lllllllll...",
      "...LlLlLlLlL...",
      "...hhhhhhhh....",
      "..Hhhhhhkkhh...",
      "..Hhhhhhhhhhh..",
      "..Hhhhhhhhhhhh.",
      "..HhhhhhhRRh...",
      "..kkkhhhhhkk...",
      "...kkkkkkkkk...",
      ".......kkkk....",
      ".........kk....",
    ],    double: [
      "..o.......o....",
      "..oo.....oo....",
      "...ooo..ooo....",
      "...lllllll.....",
      "..lllllllll....",
      ".llkylllllll...",
      ".llllllllllll..",
      "..lllLLLllllll.",
      "...LwLwLlllll..",
      "..............l",
      "...LwLwLllllll.",
      "..lllLLLllll...",
      "...lllllll.....",
    ],
    half: [
      ".....nnnnn.....",
      "....nnnnnnn....",
      "...nnNNNNNnn...",
      "...nNhhhhhNn...",
      "..nnNhkhkhNnn..",
      "..nnNhhhhhNnn..",
      "..nnNhhHhhNnn..",
      "..nnnNhhhNnnn..",
      ".nnnnnNNNnnnnn.",
      ".nnnnnnnnnnnnn.",
      "nnTnnnnynnnnTnn",
      "nnTnnnnynnnnTnn",
      "nnTnnnnnnnnnTnn",
    ],
    thief: [
      ".....ddddd.....",
      "....ddddddd....",
      "...ddLLLLLdd...",
      "...dLhhhhhLd...",
      "..ddkkkkkkkdd..",
      "..ddkwkkkwkdd..",
      "..ddLhhhhhLdd..",
      "..ddLhhhhhLdd..",
      ".dddLkkkkkLddd.",
      ".ddddkkkkkdddd.",
      "ddLdddddddddLdd",
      "ddLdddd.ddddLdd",
      "ddLdddd.ddddLdd",
    ],
  };

  const HEART = [".rr.rr.", "rxrrrrr", "rxrrrrr", "rrrrrrr", ".rrrrR.", "..rrR..", "...R..."];
  const HEART_EMPTY = [".GG.GG.", "GKGGGGG", "GKKKKKG", "GKKKKKG", ".GKKKG.", "..GKG..", "...G..."];
  const STAR = ["....y....", "...yzy...", "...yzy...", "yyyyzyyyy", ".yyzzzyy.", "..yyyyy..", "..yyYyy..", ".yyY.Yyy.", ".yY...Yy."];
  const STAR_EMPTY = ["....G....", "...GKG...", "...GKG...", "GGGGKGGGG", ".GKKKKKG.", "..GKKKG..", "..GKKKG..", ".GKG.GKG.", ".GG...GG."];
  const COIN = [".yyyy.", "yzyyyY", "yzYyyY", "yzYyyY", "yyyyYY", ".YYYY."];
  const FLAME = [
    ["...y...", "..yzy..", "..yzy..", ".yzzzy.", ".oyzyo.", ".ooyoo.", "..ooo.."],
    ["..y....", "..yy...", ".yzzy..", ".yzzzy.", ".oyzyo.", ".ooyoo.", "..ooo.."],
    ["....y..", "...yy..", "..yzzy.", ".yzzzy.", ".oyzyo.", ".ooyoo.", "..ooo.."],
  ];
  const POUCH = [
    "...nnnnn...",
    "..n.N.N.n..",
    "...nnnnn...",
    "..TTTTTTT..",
    ".TtttttttT.",
    "TttttyttttT",
    "TttttttttTT",
    "TtttttttTTT",
    ".TTTTTTTTT.",
  ];
  const HAND = [
    "....kk......",
    "...kssk.....",
    "...kssk.....",
    "...kssk.....",
    "...ksskkkkk.",
    "..kksskssksk",
    ".ksksskssksk",
    ".ksksssssssk",
    ".kssssssssSk",
    "..ksssssssSk",
    "..ksssssssSk",
    "...kSSSSSSk.",
    "...kkkkkkkk.",
  ];

  const ICONS = {
    pause: ["##.##", "##.##", "##.##", "##.##", "##.##", "##.##", "##.##"],
    play: ["#....", "##...", "###..", "####.", "###..", "##...", "#...."],
    back: ["...#...", "..##...", ".######", "#######", ".######", "..##...", "...#..."],
    restart: [".####..", "#....#.", "#...###", "#....#.", "#......", "#....#.", ".####.."],
    home: ["...#...", "..###..", ".#####.", "#######", ".#...#.", ".#.#.#.", ".#.#.#."],
    gear: ["..#.#..", ".#####.", "##...##", ".#...#.", "##...##", ".#####.", "..#.#.."],
    cards: [".####..", ".#..###", ".#..#.#", ".#..#.#", ".####.#", "...#..#", "...####"],
    lock: [".###.", "#...#", "#...#", "#####", "##.##", "##.##", "#####"],
    check: ["......#", ".....##", "#...##.", "##.##..", ".###...", "..#....", "......."],
    music: ["..####", "..#..#", "..#..#", "..#..#", "###.##", "###.##", "......"],
    sound: ["...#...", "..##.#.", "###.#.#", "###.#.#", "###.#.#", "..##.#.", "...#..."],
    calendar: ["#.#.#.#", "#######", "#.....#", "#.#.#.#", "#.....#", "#.#.#.#", "#######"],
    endless: [".......", ".##.##.", "#..#..#", "#..#..#", ".##.##.", ".......", "......."],
    map: ["##..##.", "#.##.##", "#.#..#.", "#.#..#.", "##.##.#", ".##..##", "......."],
    left: ["...#", "..##", ".###", "####", ".###", "..##", "...#"],
    close: ["#...#", "##.##", ".###.", "..#..", ".###.", "##.##", "#...#"],
    help: [".###.", "##.##", "...##", "..##.", "..#..", ".....", "..#.."],
    star: ["...#...", "..###..", "#######", ".#####.", "..###..", ".##.##.", ".#...#."],
    right: ["#...", "##..", "###.", "####", "###.", "##..", "#..."],
    market: ["#######", "#.#.#.#", "#######", ".#...#.", ".#.#.#.", ".#...#.", ".#####."],
    book: ["######.", "#....##", "#.##.##", "#....##", "#.##.##", "#....##", "######."],
  };

  // the tavern tricks, as they sit in the pouch and in the market
  const TRICKS = {
    heart: [".rr.rr...", "rxrrrrr..", "rxrrrrr..", "rrrrrrr..", ".rrrrR.s.", "..rrR.sss", "...R...s."],
    time: ["TTTTTTT", ".scccs.", ".scccs.", "..scs..", "...y...", "..sys..", ".syyys.", ".yyyyy.", "TTTTTTT"],
    peek: ["..kkkkk..", ".ksssssk.", "kssbBbssk", "ksbBkBbsk", "kssbBbssk", ".ksssssk.", "..kkkkk.."],
    broom: ["........T", ".......T.", "......T..", ".....T...", "..yyT....", ".yYyy....", "yYyYy....", "yyYy.....", ".yy......"],
  };

  const CHEST = {
    closed: [
      "..NNNNNNNNNNNNN..",
      ".NnnnnnnnnnnnnnN.",
      "NnTnnnnnnnnnnnTnN",
      "NyyyyyyyyyyyyyyyN",
      "NnTnnnnnykynnnTnN",
      "NnTnnnnnyYynnnTnN",
      "NnTnnnnnnnnnnnTnN",
      "NnTnnnnnnnnnnnTnN",
      "NyyyyyyyyyyyyyyyN",
      "NNNNNNNNNNNNNNNNN",
    ],
    open: [
      "..NNNNNNNNNNNNN..",
      ".NTTTTTTTTTTTTTN.",
      "NyyyyyyyyyyyyyyyN",
      "NzyzyyzyyyzyyzyzN",
      "yyzyYyzyzyyzYyzyy",
      "NyyyyyyyykyyyyyyN",
      "NnTnnnnnyYynnnTnN",
      "NnTnnnnnnnnnnnTnN",
      "NyyyyyyyyyyyyyyyN",
      "NNNNNNNNNNNNNNNNN",
    ],
  };

  YB.Sprites = { SUIT_SMALL, SUIT_BIG, FACES, host, SPECIAL_ART, HEART, HEART_EMPTY, STAR, STAR_EMPTY, COIN, FLAME, POUCH, HAND, ICONS, TRICKS, CHEST };
})(window.YirmibirHani);
