// hand-drawn sprites

export const HAND = [
  '....kk......',
  '...kwwk.....',
  '...kwwk.....',
  '...kwwk.....',
  '...kwwkkkkk.',
  '..kkwwkwwkwk',
  '.kwkwwkwwkwk',
  '.kwkwwwwwwwk',
  '.kwwwwwwwwwk',
  '.kwwwwwwwwWk',
  '..kwwwwwwwWk',
  '..kwwwwwwWk.',
  '...kWWWWWk..',
  '...kkkkkkk..',
];

export const MASCOT = [
  '......kk......',
  '.....kcck.....',
  '.....kcck.....',
  '....kccbbk....',
  '...kccbbbbk...',
  '..kccbbbbbbk..',
  '..kcbbbbbbbk..',
  '.kccbkbbbkbbk.',
  '.kcbbkbbbkbbk.',
  '.kcbbbbbbbbbk.',
  '.kbbpkbbbkpbk.',
  '.kbbbbkkkbbbk.',
  '..kbbbbbbbbk..',
  '..kBbbbbbbBk..',
  '...kBBBBBBk...',
  '....kkkkkk....',
];

export const MASCOT_BLINK = MASCOT.map((row, y) => (y === 7 ? '.kccbbbbbbbbk.' : row));

// 'x' marks the band that shows which water a pot needs
export const POT = [
  'kkkkkkkk',
  'knnnnnnk',
  'kNNNNNNk',
  '.kxxxxk.',
  '.kxxxxk.',
  '..kkkk..',
];

export const SPROUT = [
  '..eee..',
  '.e.E.e.',
  '...E...',
  '...E...',
];

// flowers are 7x10: head on top, stem on column 3 ending just above the pot
export const FLOWERS = {
  daisy: [
    '..www..',
    '.wwyww.',
    'wwyYyww',
    '.wwyWW.',
    '..wWW..',
    '...L...',
    '...Ll..',
    '.llL...',
    '...L...',
    '...L...',
  ],
  tulip: [
    '.r.r.r.',
    '.rrrrr.',
    '.rprrR.',
    '.rprrR.',
    '..rRR..',
    '...L...',
    '..lL...',
    '..lLl..',
    '...Ll..',
    '...L...',
  ],
  poppy: [
    '..rrr..',
    '.rrrrr.',
    'rrrkrrR',
    'rrkkkRR',
    '.rrkRR.',
    '..RRR..',
    '...L...',
    '..lL...',
    '...Lll.',
    '...L...',
  ],
  sunflower: [
    '..yyy..',
    '.yuuuy.',
    'yuuUuuy',
    'yuUuUuY',
    '.yuuuY.',
    '..yYY..',
    '...L...',
    '.llL...',
    '...Lll.',
    '...L...',
  ],
  marigold: [
    '.o.o.o.',
    'ooyoyoo',
    'oyooOyO',
    '.oOyOO.',
    '..OOO..',
    '...L...',
    '..lL...',
    '...L...',
    '..lLl..',
    '...L...',
  ],
  snowdrop: [
    '...l...',
    '..lLl..',
    '.wwwww.',
    '.wwWww.',
    '.wWWWw.',
    '.w.w.w.',
    '...L...',
    '..lL...',
    '...Ll..',
    '...L...',
  ],
  bluebell: [
    '...l...',
    '..bLb..',
    '.bcLbb.',
    '.bbLbB.',
    '.b.L.b.',
    '..bLb..',
    '.bBLBb.',
    '...L...',
    '..lL...',
    '...L...',
  ],
  edelweiss: [
    'w..w..w',
    '.wwWww.',
    '..wyw..',
    'wwyyyWW',
    '..wyw..',
    '.wW.Ww.',
    '...L...',
    '..lLl..',
    '...L...',
    '...L...',
  ],
  lavender: [
    '...v...',
    '..vVv..',
    '..vvV..',
    '..VvV..',
    '..vVv..',
    '..VvV..',
    '...L...',
    '.l.L.l.',
    '..lLl..',
    '...L...',
  ],
  moonbloom: [
    '...c...',
    '..ctc..',
    'cctwtcc',
    '.ttwtt.',
    '..tct..',
    '.c...c.',
    '...L...',
    '..lL...',
    '...Ll..',
    '...L...',
  ],
  rose: [
    '..ppp..',
    '.pPPPp.',
    'pPpppPp',
    'pPpPpPP',
    '.pPPPP.',
    '..PPP..',
    '...L...',
    '.lLL...',
    '...Ll..',
    '...L...',
  ],
  iris: [
    '..v.v..',
    '.vVvVv.',
    '..vVv..',
    'vvvyvvv',
    'vVv.vVv',
    '.v...v.',
    '...L...',
    '..lL...',
    '...Ll..',
    '...L...',
  ],
};

// stem and leaf letters keep their colour on golden flowers
export const STEM_LETTERS = new Set(['l', 'L', 'd']);

export const OBSTACLES = {
  meadow: [
    '....kkkkkk....',
    '..kkllllllkk..',
    '.klllwlllllLk.',
    '.kllllllrlLLk.',
    'kllrllllllllLk',
    'klllllllllLLLk',
    'kLlllllrllLLLk',
    'kLLllllllLLLLk',
    '.kLLLLLLLLLLk.',
    '.kdLLLLLLLLdk.',
    '..kkddddddkk..',
    '....kkkkkk....',
  ],
  canyon: [
    '....kkkkk.....',
    '..kkhhhaakk...',
    '.khhhaaaaaAk..',
    '.khaaaaaaaAAk.',
    'khaaaaAaaaaAk.',
    'khaaaAAaaaaAAk',
    'kaaaaaaaaaAAAk',
    'kAaaaaaaaAAAAk',
    '.kAAAaaaAAAAk.',
    '..kkAAAAAAkk..',
    '....kkkkkk....',
  ],
  frost: [
    '...kkkkkkkk...',
    '..kjjjjjjjjk..',
    '.kjwjjjjjjjjk.',
    'kjjjjjjjjjjjik',
    'kiiiiiiiiiiIIk',
    'kiwiiiiiiiiIIk',
    'kiiwiiiiiiiIIk',
    'kiiiiiiiiiiIIk',
    'kiiiiiiiiiiIIk',
    'kIiiiiiiiiiIIk',
    '.kIIIIIIIIIIk.',
    '..kkkkkkkkkk..',
  ],
  twilight: [
    '...kkkkkk.....',
    '.kkttwtttkk...',
    'kttttttwttTk..',
    'ktwttttttTTk..',
    'kTTTTTTTTTTk..',
    '.kkkkmmkkkk...',
    '....kmmk.kkk..',
    '....kmmkkttTk.',
    '....kmmkkTTTk.',
    '....kmMk.kmk..',
    '...kmmMMkkmk..',
    '...kkkkkkkkk..',
  ],
  sky: [
    '......kk......',
    '.....kwvk.....',
    '.....kwvk.....',
    '..k..kwvVk....',
    '.kvk.kwvVk.k..',
    '.kwvkkwvVkkvk.',
    '.kwvVkwvVkwvk.',
    '.kwvVkwvVkwVk.',
    '.kwvVkwvVkvVk.',
    'kkkkkkkkkkkkkk',
    'kWWWWWWWWWWWGk',
    '.kkkkkkkkkkkk.',
  ],
};

// small glyphs that tell rune groups apart without relying on colour
export const RUNES = [
  ['.x.', 'x.x', '.x.'],
  ['xxx', 'x.x', 'xxx'],
  ['.x.', 'xxx', '.x.'],
  ['x.x', '.x.', 'x.x'],
  ['.x.', 'x.x', 'xxx'],
];

export const STAR = [
  '....y....',
  '....y....',
  '...yyy...',
  'yyyywyyyy',
  '.yyyyyyy.',
  '..yyyyY..',
  '..yyyYY..',
  '.yyY.YYY.',
  '.yY...YY.',
];

export const DEWDROP = [
  '...c...',
  '..ccb..',
  '..cbb..',
  '.cwbbb.',
  '.cwbbb.',
  'cwbbbbB',
  'cbbbbbB',
  '.bbbBB.',
  '..BBB..',
];

export const LOCK = [
  '..GGG..',
  '.G...G.',
  '.G...G.',
  'ggggggg',
  'gggkggg',
  'gggkggG',
  'gggggGG',
  '.GGGGG.',
];

export const FLAME = [
  '...r...',
  '..rr...',
  '..ror..',
  '.rroor.',
  '.rooor.',
  'rrooyor',
  'royyyor',
  'royyyor',
  '.ryyyr.',
];

export const SUN = [
  '....o....',
  '.o.....o.',
  '...yyy...',
  '..yyyyy..',
  'o.yyyyY.o',
  '..yyyYY..',
  '...YYY...',
  '.o.....o.',
  '....o....',
];

export const LEAF = [
  '......LLL',
  '....LLllL',
  '...LlllLL',
  '..LlllLlL',
  '..LllLllL',
  '.LllLllL.',
  '.LlLllLL.',
  '.LLLLL...',
  'L........',
];

// single-colour UI icons, drawn in ink on buttons
export const ICONS = {
  play: [
    '..x......',
    '..xx.....',
    '..xxx....',
    '..xxxx...',
    '..xxxxx..',
    '..xxxx...',
    '..xxx....',
    '..xx.....',
    '..x......',
  ],
  pause: [
    '.........',
    '.xxx.xxx.',
    '.xxx.xxx.',
    '.xxx.xxx.',
    '.xxx.xxx.',
    '.xxx.xxx.',
    '.xxx.xxx.',
    '.xxx.xxx.',
    '.........',
  ],
  undo: [
    '..x......',
    '.xx......',
    'xxxxxxx..',
    '.xx....x.',
    '..x.....x',
    '........x',
    '........x',
    '.......x.',
    '..xxxxx..',
  ],
  restart: [
    '..xxxx.x.',
    '.x....xx.',
    'x....xxx.',
    'x........',
    'x........',
    'x.......x',
    '.x.....x.',
    '..xxxxx..',
    '.........',
  ],
  home: [
    '....x....',
    '...xxx...',
    '..xxxxx..',
    '.xxxxxxx.',
    'xxxxxxxxx',
    '.xxxxxxx.',
    '.xx...xx.',
    '.xx...xx.',
    '.xx...xx.',
  ],
  grid: [
    'xx.xx.xx.',
    'xx.xx.xx.',
    '.........',
    'xx.xx.xx.',
    'xx.xx.xx.',
    '.........',
    'xx.xx.xx.',
    'xx.xx.xx.',
    '.........',
  ],
  gear: [
    '....x....',
    '.x.xxx.x.',
    '..xxxxx..',
    '.xx...xx.',
    'xxx...xxx',
    '.xx...xx.',
    '..xxxxx..',
    '.x.xxx.x.',
    '....x....',
  ],
  music: [
    '...xxxxxx',
    '...xxxxxx',
    '...x....x',
    '...x....x',
    '...x....x',
    '.xxx..xxx',
    'xxxx.xxxx',
    'xxx..xxx.',
    '.........',
  ],
  sound: [
    '...x.....',
    '..xx...x.',
    'xxxx.x..x',
    'xxxx..x.x',
    'xxxx..x.x',
    'xxxx.x..x',
    '..xx...x.',
    '...x.....',
    '.........',
  ],
  back: [
    '.........',
    '...x.....',
    '..xx.....',
    '.xxxxxxxx',
    'xxxxxxxxx',
    '.xxxxxxxx',
    '..xx.....',
    '...x.....',
    '.........',
  ],
  next: [
    '.........',
    '.....x...',
    '.....xx..',
    'xxxxxxxx.',
    'xxxxxxxxx',
    'xxxxxxxx.',
    '.....xx..',
    '.....x...',
    '.........',
  ],
  close: [
    'xx.....xx',
    'xxx...xxx',
    '.xxx.xxx.',
    '..xxxxx..',
    '...xxx...',
    '..xxxxx..',
    '.xxx.xxx.',
    'xxx...xxx',
    'xx.....xx',
  ],
  check: [
    '.........',
    '.......xx',
    '......xxx',
    '.....xxx.',
    'xx..xxx..',
    'xxxxxx...',
    '.xxxx....',
    '..xx.....',
    '.........',
  ],
  book: [
    '.xxx.xxx.',
    'x...x...x',
    'x.xxx.x.x',
    'x...x...x',
    'x.xxx.x.x',
    'x...x...x',
    'x.xxx.x.x',
    'xxxxxxxxx',
    '....x....',
  ],
};
